project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 00"
        href: Hands-on_Ex/Hands-on_Ex00.html
      - text: "Hands-on Exercise 01"
        href: Hands-on_Ex/Hands-on_Ex01.html
      - text: "Hands-on Exercise 02"
        href: Hands-on_Ex/Hands-on_Ex02.html
      - text: "Hands-on Exercise 03a"
        href: Hands-on_Ex/Hands-on_Ex03a.html
      - text: "Hands-on Exercise 03b"
        href: Hands-on_Ex/Hands-on_Ex03b.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex/In-class_Ex01.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take Home Exercise 1"
        href: Take-home_Ex01.html
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

editor: visual

