project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 00"
        href: Hands-on_Ex/Hands-on_Ex00.html
      - text: "Hands-on Exercise 01"
        href: Hands-on_Ex/Hands-on_Ex01.html
      - text: "Hands-on Exercise 02"
        href: Hands-on_Ex/Hands-on_Ex02.html
      - text: "Hands-on Exercise 03a"
        href: Hands-on_Ex/Hands-on_Ex03a.html
      - text: "Hands-on Exercise 03b"
        href: Hands-on_Ex/Hands-on_Ex03b.html
      - text: "Hands-on Exercise 04a"
        href: Hands-on_Ex/Hands-on_Ex04a.html
      - text: "Hands-on Exercise 04b"
        href: Hands-on_Ex/Hands-on_Ex04b.html
      - text: "Hands-on Exercise 04c"
        href: Hands-on_Ex/Hands-on_Ex04c.html
      - text: "Hands-on Exercise 04d"
        href: Hands-on_Ex/Hands-on_Ex04d.html
      - text: "Hands-on Exercise 05a"
        href: Hands-on_Ex/Hands-on_Ex05a.html
      - text: "Hands-on Exercise 05b"
        href: Hands-on_Ex/Hands-on_Ex05b.html
      - text: "Hands-on Exercise 05c"
        href: Hands-on_Ex/Hands-on_Ex05c.html
      - text: "Hands-on Exercise 05d"
        href: Hands-on_Ex/Hands-on_Ex05d.html
      - text: "Hands-on Exercise 05e"
        href: Hands-on_Ex/Hands-on_Ex05e.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise Outline"
        href: In-class_Ex/In-class_Outline.html
      - text: "In-class Exercise 01"
        href: https://public.tableau.com/views/In-class_Ex01_17371867213230/Dashboard1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "In-class Exercise 02"
        href: https://public.tableau.com/views/In-class_Ex02_17377896182080/Dashboard2?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "In-class Exercise 03"
        href: https://public.tableau.com/views/In-class_Ex03_17383925295110/Hands-on_Ex03?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "In-class Exercise 03-Story"
        href: https://public.tableau.com/views/In-class_Ex03_Story/Myfirststory?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "In-class Exercise 03-Animation"
        href: https://public.tableau.com/views/In-class_Ex03_Animation/Dashboard6?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "In-class Exercise 04"
        href: In-class_Ex/In-class_Ex04.html
      - text: "In-class Exercise 05"
        href: In-class_Ex/In-class_Ex05.html
      - text: "In-class Exercise 05 Tableau"
        href: https://public.tableau.com/views/In-class_Ex05_17397001428450/Realis2018?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
    - text: "Take-home Exercise"
      menu:
      - text: "Take Home Exercise 1"
        href: Take-home_Ex/Take-home_Ex01.html
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    code-tools: true

editor: visual

