project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 00"
        href: Hands-on_Ex/Hands-on_Ex00.html
      - text: "Hands-on Exercise 01"
        href: Hands-on_Ex/Hands-on_Ex01.html
      - text: "Hands-on Exercise 02"
        href: Hands-on_Ex/Hands-on_Ex02.html
      - text: "Hands-on Exercise 03a"
        href: Hands-on_Ex/Hands-on_Ex03a.html
      - text: "Hands-on Exercise 03b"
        href: Hands-on_Ex/Hands-on_Ex03b.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise Outline"
        href: In-class_Ex/In-class_Outline.html
      - text: "In-class Exercise 01"
        href: https://public.tableau.com/views/In-class_Ex01_17371867213230/Dashboard1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "In-class Exercise 02"
        href: https://public.tableau.com/views/In-class_Ex02_17377896182080/Dashboard2?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
    - text: "Take-home Exercise"
      menu:
      - text: "Take Home Exercise 1"
        href: Take-home_Ex01.html
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

editor: visual

