---
title: "In-class Exercise 04"
author: "Andrea Yeo"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

## 1. Getting started

### 1.1 Installing and loading of R packages

```{r}
pacman::p_load(haven, SmartEDA,tidyverse, tidymodels,ggridges, colorspace)
```

#### 1.2  Importing data

```{r}
exam <- read_csv("data/Exam_data.csv", show_col_types = FALSE)
```

### 1.3 Visualing the target

```{r}
ggplot(data = exam,
       aes(x = ENGLISH,
           y = CLASS)) +
  geom_boxplot()
```
### 1.4 Enhance the visualization of the target

```{r}
ggplot(data = exam, aes(x = ENGLISH, y = CLASS)) +
  geom_boxplot(fill = "#7097BB", color = "black", alpha = 0.6, outlier.shape = NA) +  # Boxplot with color
  geom_jitter(aes(color = CLASS), width = 0.2, alpha = 0.7, size = 2) +  # Add jittered points
  scale_color_brewer(palette = "Dark2") +  # Use Brewer palette for distinct colors
  labs(
    title = "Distribution of English Grades by Class",
    x = "English Grades",
    y = "Class"
  ) +
  theme_minimal() +  # Modern theme
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),  # Centered title
    legend.position = "none"  # Hide legend if not needed
  )
```

### 1.5 Explore the ridgeline graph

```{r}
ggplot(data = exam, aes(x = ENGLISH, y = CLASS)) +
  geom_density_ridges(
    scale = 3,
    rel_min_height = 0.01,
    bandwidth = 3.4,
    fill = lighten("#7097BB", .3),
    color = "white"
  ) +
  scale_x_continuous(
    name = "English grades",
    expand = c(0, 0)
  ) +
  scale_y_discrete(
    name = NULL, 
    expand = expansion(add = c(0.2, 2.6))
  ) +
  theme_ridges()
```


